apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: uloe-mongodb
  name: uloe-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uloe-mongodb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: uloe-mongodb
    spec:
      containers:
      - image: linuxacademycontent/uloe-mongodb:1.0.0
        name: uloe-mongodb
        ports:
        - containerPort: 27017
        resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: uloe-mongodb
spec:
  type: ClusterIP
  selector:
    app: uloe-mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
